[tools]
go = "1.23.2"            # Specify the Go version you want to use
golangci-lint = "1.61.0" # Add this line

[tasks.llm_helper_generate_output_txt]
run = "repo2txt --exclude-dir  public resources node_modules pb_data vendor --ignore-files package-lock.json spec.md go.sum image-dupes  --ignore-types .db"
description = 'Remove all the various output.txts'                                                                                                           # hide this task from the list


[tasks]
build = "go build"
test = "go test -v ./... -coverprofile=coverage.out -covermode=atomic && go tool cover -html=coverage.out -o coverage.html"
clean = "go clean && rm -f image-dupes"
lint = "golangci-lint run"
lint-fix = "golangci-lint run --fix"
lint-all = "golangci-lint run --enable-all"
lint-all-fix = "golangci-lint run --enable-all --fix"
run = "go run *.go"
deps = "go get ./... && go mod tidy"
all = { depends = ["lint", "test", "build"] }
